### ISSUE TITLE
Print warning when the alignment lattice wont get built

### ISSUE THREAD

**Issue by jtrmal** [AdolfVonKleist/Phonetisaurus#22] opened 2017-08-08 16:19 UTC
For syllabic languages (and perhaps other languages with a more complex pronunciation rules), the default setting seq1_max=2 and seq2_max=2 is sometimes not sufficient -- the alignment lattice, in that case, won't get even constructed. However, phonetisaurus is completely silent about this. 
I think it would be good to issue a warning so that user would know something is going on.

**Comment by AdolfVonKleist** [comment] 2017-08-27 18:49
I've merged a new [commit](https://github.com/AdolfVonKleist/Phonetisaurus/pull/29) into master that includes this fix.  The ```phonetisaurus-align``` tool now prints a warning message to stderr, ```Alignment failed: W A G A```, for each word-pron pair that cannot be aligned due to the default/user-defined multigram size constraints.  The ```phonetisaurus_train``` script also prints this, but only when called with the ```--verbose``` flag.  I also added a boolean option to the aligner and script, ```--grow```, set to  ```false``` by default, which when set to ```true``` will cause the aligner to iteratively increase the max alignment arguments until each pair can be aligned.

A ```test``` directory is added which contains a small regression for the g014b2b set.  There is no noticeable difference at 1-best whether the ```--grow``` flag is used or not, but it may be useful in some cases with enough training data, and/or use of n-best.

I haven't updated the ```kaldi``` tag yet, so this will not be pulled in automatically yet.  But I will update that if this resolves your issue.

**Comment by AdolfVonKleist** [comment] 2017-08-31 09:23
I'm assuming this is OK now @jtrmal , and resolved in the referred commit.  The new build updates in the latest [PR](https://github.com/AdolfVonKleist/Phonetisaurus/pull/27) from @giuliopaci also should resolve remaining compilation issues related to rpath.

**Closed by AdolfVonKleist** 2017-08-31 09:23 UTC

**Comment by jtrmal** [comment] 2017-09-05 14:43
cool, thanks for the change. Apologies for not being able to respond faster
-- we were close to evaluation deadline.
I'll play with it probably early next week.
y.
